# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  helloworld:
    image: helloworld
    build:
      context: .
      dockerfile: HelloWorld/Dockerfile
    ports:
      - 80:80
      - 443:443
